sgCibercachadas/sgCibercachadas/etl/urls.py
from django.urls import include,path
from etl.views import *

urlpatterns = [
    path('',CargaDatos.as_view(),name="carga_menu"),
    path('cargabd',EtlBD.as_view(),name="etl_bd"),
    path('cargaretorno',CargaRetorno.as_view(),name='etl_retorno'),
    path('cargapotencial',CargaPotencial.as_view(),name='etl_potencial'),
    path('cargaconsigna',CargaConsigna.as_view(),name='etl_consigna')
    

]

sgCibercachadas/sgCibercachadas/sgCibercachadas/urls.py
from django.urls import include,path

urlpatterns = [
    path('',include(('general.urls','general'),namespace='general')),
    path('resumen/',include(('estrategico.urls','estrategico'),namespace='estrategico')),
    path('semiresumen/',include(('tactico.urls','tactico'),namespace='tactico')),
    path('admin/',include(('administrador.urls','administrador'),namespace='administrador')),
    path('etl/',include(('etl.urls','etl'),namespace='etl'))
]

sgCibercachadas/sgCibercachadas/tactico/urls.py
from django.urls import include, path
from tactico.views import *

urlpatterns = [
    path('productosmasvendidos',ProductosMasVendidosView.as_view(),name='semire_producto_mas_vendidos'),
    path('productosgeneranganancia',ProductosGeneranGananciaView.as_view(),name='semire_producto_generan_ganancia'),
    path('retornoequiposgarantia',RetornoEquiposGarantiaView.as_view(),name='semire_retorno_equipos_garantia'),
    path('productosenconsigna',RetornoEnConsignaView.as_view(),name='semire_productos_consigna'),
    path('clientesganancia',ClientesGananciaView.as_view(),name='semire_clientes_ganancia'),
    path('clientesfrecuentes',ClientesFrecuentesView.as_view(),name='semire_clientes_frecuentes'),
]

sgCibercachadas/sgCibercachadas/estrategico/forms.py
from django import forms
from collections import Counter
from datetime import datetime

class FechasForm(forms.Form):
    fechainicio=forms.CharField(widget=forms.TextInput(attrs={"name":"fechainicio" ,
    "class":"form-control col-6","placeholder":"Seleccione fecha","autocomplete":"off",}))
    fechafin=forms.CharField(widget=forms.TextInput(attrs={"name":"fechafin" ,
    "class":"form-control col-6","placeholder":"Seleccione fecha","autocomplete":"off"},))
    
    def AddIsInvalid(self):
            for field in self.errors:
                self[field].field.widget.attrs['class'] += ' is-invalid'
            print(self.fields)


    def clean_fechafin(self):
        
        fechafin = self.cleaned_data.get("fechafin")
        fechafin=datetime.strptime(fechafin,'%d/%m/%Y')

        if fechafin>datetime.today():
            raise forms.ValidationError("La fecha final es superior a la fecha de hoy")
        
        return fechafin


    def clean(self):
        cleaned_data = super().clean()

        fechainicio =cleaned_data.get("fechainicio")
        
        if fechainicio:
            fechainicio=datetime.strptime(fechainicio,'%d/%m/%Y')

        fechafin = self.cleaned_data.get("fechafin")

        #si no es none
        if fechafin and fechainicio:
            if fechafin<fechainicio:
                self.add_error('fechainicio',"La fecha inicial es mayor que la fecha final")
       


class CategoriaForm(FechasForm):
    categoria=forms.ChoiceField(choices=())

sgCibercachadas/sgCibercachadas/tactico/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.views import generic
from estrategico.forms import FechasForm
from general.reporte import plantilla_reporte
from general.excel import hoja_calculo
from django.contrib import messages
from datetime import datetime
from gerencial.models import *
from django.db.models import Sum,Count,Q
from estrategico.forms import  FechasForm
from plantilla_reporte.tacticopdf import producto_vendido, producto_ganancia,producto_retorno,producto_cliente,producto_consigna,cliente_frecuente
from plantilla_reporte.tacticoxls import producto_vendidoxls, producto_gananciaxls,producto_retornoxls,producto_consignaxls,producto_clientexls,cliente_frecuentexls
from plantilla_reporte.funciones.funciones import agrupar_cliente_tactico, agrupar_cliente_frecuente
import operator
from django.http import JsonResponse

# Create your views here.

class ProductosMasVendidosView(LoginRequiredMixin,PermissionRequiredMixin, generic.TemplateView):
    template_name='tactico/productos_mas_vendidos.html'
    login_url='general:login'
    permission_required = 'gerencial.semi_productos_vendidos'

    def get(self,request,*args,**kwargs):
        form=FechasForm()
        fecha=datetime.now()
        fecha=datetime.strftime(fecha,'%d/%m/%Y')
        categoria = Categoria.objects.all()
        return render(request, self.template_name, {'form': form,'fecha':fecha,'categoria':categoria})

    def post(self, request, *args, **kwargs):
        form = FechasForm(request.POST)
        if form.is_valid():
            print("valido")
        else:
            if request.is_ajax():
                return JsonResponse(form.errors.as_json(),safe=False)
            else:
                form.AddIsInvalid()
                return render(request, self.template_name, {'form':form})

        inicio=request.POST.get("fechainicio",None)
        fin=request.POST.get("fechafin",None)
        tipo=int(request.POST.get("tipo",None))
        categoria = request.POST.get('categoria',None)

        fecha_inicio = datetime.strptime(inicio,'%d/%m/%Y')
        fecha_inicio = datetime.strftime(fecha_inicio,'%Y-%m-%d %H:%M:%S')

        fecha_fin = datetime.strptime(fin,'%d/%m/%Y')
        fecha_fin = datetime.strftime(fecha_fin,'%Y-%m-%d %H:%M:%S')
        
        if(categoria):
            detalle_vendido = list(DetalleVenta.objects.filter(Q(idVenta__fecha_hora__range=(fecha_inicio,fecha_fin)) & Q(idProducto__idCategoria__nombre=categoria)).values('idProducto__nombre','idProducto').annotate(Sum('total'),Sum('cantidad')))
        else: 
            detalle_vendido = list(DetalleVenta.objects.filter(idVenta__fecha_hora__range=(fecha_inicio,fecha_fin)).values('idProducto__nombre','idProducto__idCategoria__nombre','idProducto').annotate(Sum('total'),Sum('cantidad')))
               
        fecha_fin = datetime.strptime(fin,'%d/%m/%Y')
        fecha_fin = datetime.strftime(fecha_fin,'%Y-%m-%d')
        for det in detalle_vendido:
            prod = Kardex.objects.filter(Q(fecha__lte=fecha_fin)& Q(idProducto=det['idProducto'])).order_by('-fecha').first()
            if(prod):
                det['costo'] = prod.precExistencia
                det['inventario'] = prod.cantExistencia
            else:
                det['costo'] = 0  
                det['inventario'] = 0
            ganancia = det['total__sum']-(det['cantidad__sum']*det['costo'])
            det['ganancia'] = ganancia
        
        detalle_vendido.sort(key=producto_vendido.clave_orden,reverse=True)
        if(tipo==1):
            return JsonResponse(detalle_vendido[:10],safe=False)
        elif(tipo==2):
            if(detalle_vendido):
                #bitacora 
                Bitacora.objects.create(
                usuario=request.user.first_name+" "+request.user.last_name,
                accion="reporte tactico: productos mas vendidos (pdf)")

                return producto_vendido.reporte(request,detalle_vendido[:30],'producto_vendido_tactico',inicio,fin,categoria)
            else:
                messages.add_message(request, messages.WARNING, 'No se encontraron datos en el periodo seleccionado')
                return redirect(self.request.path_info)
        elif(tipo==3):
            if(detalle_vendido):
                
                #bitacora 
                Bitacora.objects.create(
                usuario=request.user.first_name+" "+request.user.last_name,
                accion="reporte tactico: productos mas vendidos (xls)")

                return producto_vendidoxls.hoja_calculo(request,detalle_vendido[:30],'producto_vendido_tactico',inicio,fin,categoria)
            else:
                messages.add_message(request, messages.WARNING, 'No se encontraron datos en el periodo seleccionado')
                return redirect(self.request.path_info)
        else:
            messages.add_message(request, messages.WARNING, 'Esta opción no es valida')
            return redirect(self.request.path_info)

class ProductosGeneranGananciaView(LoginRequiredMixin,PermissionRequiredMixin,generic.TemplateView):
    template_name='tactico/productos_generan_ganancias.html'
    login_url='general:login'
    permission_required = 'gerencial.semi_productos_ganancias'

    def get(self,request,*args,**kwargs):
        form=FechasForm()
        fecha=datetime.now()
        fecha=datetime.strftime(fecha,'%d/%m/%Y')
        categoria = Categoria.objects.all()
        return render(request, self.template_name, {'form': form,'fecha':fecha,'categoria':categoria})

    def post(self, request, *args, **kwargs):
        form = FechasForm(request.POST)
        if form.is_valid():
            print("valido")
        else:
            if request.is_ajax():
                return JsonResponse(form.errors.as_json(),safe=False)
            else:
                form.AddIsInvalid()
                return render(request, self.template_name, {'form':form})

        inicio=request.POST.get("fechainicio",None)
        fin=request.POST.get("fechafin",None)
        tipo=int(request.POST.get("tipo",None))
        categoria = request.POST.get('categoria',None)

        fecha_inicio = datetime.strptime(inicio,'%d/%m/%Y')
        fecha_inicio = datetime.strftime(fecha_inicio,'%Y-%m-%d %H:%M:%S')

        fecha_fin = datetime.strptime(fin,'%d/%m/%Y')
        fecha_fin = datetime.strftime(fecha_fin,'%Y-%m-%d %H:%M:%S')
        
        if(categoria):
            detalle_vendido = list(DetalleVenta.objects.filter(Q(idVenta__fecha_hora__range=(fecha_inicio,fecha_fin)) & Q(idProducto__idCategoria__nombre=categoria)).values('idProducto__nombre','idProducto').annotate(Sum('total'),Sum('cantidad')))
        else: 
            detalle_vendido = list(DetalleVenta.objects.filter(idVenta__fecha_hora__range=(fecha_inicio,fecha_fin)).values('idProducto__nombre','idProducto__idCategoria__nombre','idProducto').annotate(Sum('total'),Sum('cantidad')))
        
        fecha_fin = datetime.strptime(fin,'%d/%m/%Y')
        fecha_fin = datetime.strftime(fecha_fin,'%Y-%m-%d')

        for det in detalle_vendido:
            prod = Kardex.objects.filter(Q(fecha__lte=fecha_fin)& Q(idProducto=det['idProducto'])).order_by('-fecha').first()
            if(prod):
                det['costo'] = prod.precExistencia
                det['inventario'] = prod.cantExistencia
            else:
                det['costo'] = 0  
                det['inventario'] = 0
            ganancia = det['total__sum']-det['cantidad__sum']*det['costo']
            det['ganancia'] = ganancia
        
        detalle_vendido.sort(key=producto_ganancia.clave_orden,reverse=True)
        if(tipo==1):
            return JsonResponse(detalle_vendido[:10],safe=False)

        elif(tipo==2):
            if(detalle_vendido):
                
                #bitacora 
                Bitacora.objects.create(
                usuario=request.user.first_name+" "+request.user.last_name,
                accion="reporte tactico: productos ganancia (pdf)")

                return producto_ganancia.reporte(request,detalle_vendido[:30],'producto_ganancia_tactico',inicio,fin,categoria)
            else:
                messages.add_message(request, messages.WARNING, 'No se encontraron datos durante este periodo')
                return redirect(self.request.path_info)
        elif(tipo==3):
            if(detalle_vendido):
                
                #bitacora 
                Bitacora.objects.create(
                usuario=request.user.first_name+" "+request.user.last_name,
                accion="reporte tactico: productos ganancia (xls)")

                return producto_gananciaxls.hoja_calculo(request,detalle_vendido[:30],'producto_ganancia_tactico',inicio,fin,categoria)
            else:
                messages.add_message(request, messages.WARNING, 'No se encontraron datos durante este periodo')
                return redirect(self.request.path_info)
        else:
            messages.add_message(request, messages.WARNING, 'Esta opción no es valida')
            return redirect(self.request.path_info)

class RetornoEquiposGarantiaView(LoginRequiredMixin,PermissionRequiredMixin,generic.TemplateView):
    template_name='tactico/retorno_equipos_garantia.html'
    login_url='general:login'
    permission_required = 'gerencial.semi_retornos_equipos'

    def get(self,request,*args,**kwargs):
        form=FechasForm()
        fecha=datetime.now()
        fecha=datetime.strftime(fecha,'%d/%m/%Y')
        categoria = Categoria.objects.all()
        return render(request, self.template_name, {'form': form,'fecha':fecha,'categoria':categoria})

    def post(self, request, *args, **kwargs):
        form = FechasForm(request.POST)
        if form.is_valid():
            print("valido")
        else:
            if request.is_ajax():
                return JsonResponse(form.errors.as_json(),safe=False)
            else:
                form.AddIsInvalid()

sgCibercachadas/sgCibercachadas/tactico/templates/tactico/clientes_frecuentes.html
{% extends 'base/base.html' %}
{% block head_title %}
SCF
{% endblock head_title %}
{% block titulo_principal %}
Clientes Frecuentes
{% endblock titulo_principal %}
{% block mensaje_titulo %}
Semiresumen de Ganancia por cliente con fechas establecidas y Categoria seleccionada
{% endblock mensaje_titulo %}
{% block enlace_actual %}
<a href="{% url 'tactico:semire_clientes_frecuentes' %}">Clientes Frecuentes</a>
{% endblock enlace_actual %}
{% block contenido %}
{% if messages %}
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-{{ message.tags }} text-center"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
{% endif %}
<div class="container">
        <div class="text-center container-central">
                <label class="control-label" id="label_custom">Clientes Frecuentes</label>
                <p>{{fecha}}</p>
        </div>
    <form action="" method="post">
        {% csrf_token %}
        {% include "base/fechas_snippet.html" %}
        
       
    
        <div class="row">
            <div class="col-12">
                <div class="row ">
                    <div class="col-4">
                        <button name="tipo" class="btn btn-default boton-custom" type="submit" value="1">Preview <i class="fa fa-eye fa-2x"  aria-hidden="true"></i></button>
                    </div>
                    <div class="col-4">
                        <button name="tipo" class="btn btn-primary boton-custom" type="submit" value="2">Generar Reporte en PDF  <i class="fa fa-file-pdf-o fa-2x"  aria-hidden="true"></i></button>
                    </div>
                    <div class="col-4">
                        <button name="tipo" class="btn btn-success boton-custom" type="submit" value="3">Generar Reporte en xls <i class="fa fa-file-excel-o fa-2x"  aria-hidden="true"></i></button>
                    </div>    
                </div>
            </div>
        </div>

    </form>
</div>
    {% endblock contenido %}


    {% block plugins %}

    {% include "base/conf_fechas.html" %}

    {% endblock plugins %}

sgCibercachadas/sgCibercachadas/tactico/templates/tactico/productos_consigna.html
{% extends 'base/base.html' %}
{% block head_title %}
SPC
{% endblock head_title %}
{% block titulo_principal %}
Productos en consigna
{% endblock titulo_principal %}
{% block mensaje_titulo %}
Semiresumen de Productos en consigna con fechas establecidas y Categoria seleccionada
{% endblock mensaje_titulo %}
{% block enlace_actual %}
<a href="{% url 'tactico:semire_productos_consigna' %}">Productos en consigna</a>
{% endblock enlace_actual %}
{% block contenido %}
{% if messages %}
{% for message in messages %}
<li{% if message.tags %} class="alert alert-{{ message.tags }} text-center" {% endif %}>
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
    {{ message }}
    </li>
    {% endfor %}
    {% endif %}
    <div class="container">
        <div class="text-center container-central">
            <label class="control-label" id="label_custom">Productos en consigna</label>
            <p>{{fecha}}</p>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {% include "base/fechas_snippet.html" %}


            <div class="row">
                <div class="col-12">
                    <div class="row ">
                        <div class="col-4">
                            <button name="tipo" class="btn btn-default boton-custom"  type="button" onclick="preview()" value="1">Preview <i
                                class="fa fa-eye fa-2x" aria-hidden="true"></i></button>
                        </div>
                        <div class="col-4">
                            <button name="tipo" class="btn btn-primary boton-custom" type="submit" value="2">Generar
                                Reporte en PDF <i class="fa fa-file-pdf-o fa-2x" aria-hidden="true"></i></button>
                        </div>
                        <div class="col-4">
                            <button name="tipo" class="btn btn-success boton-custom" type="submit" value="3">Generar
                                Reporte en xls <i class="fa fa-file-excel-o fa-2x" aria-hidden="true"></i></button>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>

    
    <div class="container" style="position: relative; top:20px; display:none" id='id_tile'>
        <div class="tile" style="border: black solid">
                <h3 class="tile-title">Preview</h3>
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>Nombre</th>
                      <th>Categoria</th>
                      <th>Fecha inicio</th>
                      <th>Fecha Fin</th>
                      <th>Cliente</th>
                      <th>Cantidad</th>
                    </tr>
                  </thead>
                  <tbody id='table'>

                  </tbody>
                </table>
              </div>
</div>
    {% endblock contenido %}


    {% block plugins %}

    {% include "base/conf_fechas.html" %}
    <script type="text/javascript">
        // using jQuery get csrftoken from your HTML
            var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    // if not safe, set csrftoken
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            function preview(){


                $.ajax({
                    url: "{% url 'tactico:semire_productos_consigna' %}",
                    method:'POST',
                    data: {
                        // here getdata should be a string so that
                        // in your views.py you can fetch the value using get('getdata')
                        'tipo': 1,
                        'fechainicio':$("#id_fechainicio").val(),
                        'fechafin':$("#id_fechafin").val()


                    },
                    dataType: 'json',
                    success: function (res, status) {
                        if(Array.isArray(res)){
                            $("#error_fechainicio").hide()
                            $("#error_fechafin").hide()
                            $("#id_tile").show()
                            console.log(res)
                            var table=$("#table");
                            $("#table").html("")
                            res.forEach(function(elemento){
                            table.append("<tr><td>"+elemento.idProducto__nombre+"</td><td>"
                            +elemento.idProducto__idCategoria__nombre+
                            "</td>   <td>"+elemento.fechaInicio+
                            "</td><td>"+elemento.fechaFin+"</td><td>"+elemento.idCliente__nombre+"</td><td>"
                            +elemento.cantidad__sum+"</td></tr>");
                            }
                            );
                        }
                        else{
                            $("#error_fechainicio").hide()
                            $("#error_fechafin").hide()
                            $("#id_tile").hide()
                           
                            obj=JSON.parse(res)
                            if(obj.fechafin!=null){
                                $("#error_fechafin").show()
                                $("#error_fechafin").html(obj.fechafin[0].message)
                            }
                            if(obj.fechainicio!=null){
                                $("#error_fechainicio").show()
                                $("#error_fechainicio").html(obj.fechainicio[0].message)
                            }
                        }
                    },
                    error: function (res) {
                        console.log(res);                                                                                                                          
                    }
                });
            }
        </script>
    {% endblock plugins %}

sgCibercachadas/sgCibercachadas/tactico/templates/tactico/productos_generan_ganancias.html
{% extends 'base/base.html' %}
{% block head_title %}
SPGMG
{% endblock head_title %}
{% block titulo_principal %}
Productos que generan mas ganancias
{% endblock titulo_principal %}
{% block mensaje_titulo %}
Semiresumen de Productos que generan mas ganancias con fechas establecidas y Categoria seleccionada
{% endblock mensaje_titulo %}
{% block enlace_actual %}
<a href="{% url 'tactico:semire_producto_generan_ganancia' %}">productos que generan mas ganancias</a>
{% endblock enlace_actual %}
{% block contenido %}
{% if messages %}
{% for message in messages %}
<li{% if message.tags %} class="alert alert-{{ message.tags }} text-center" {% endif %}>
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
    {{ message }}
    </li>
    {% endfor %}
    {% endif %}
    <div class="container">
        <div class="text-center container-central">
            <label class="control-label" id="label_custom">Productos que generan mas ganancias</label>
            <p>{{fecha}}</p>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {% include "base/fechas_snippet.html" %}

            <div class="container-central">
                <div class="row justify-content-center ">
                    <div class="col-1">
                        <label class="control-label " id="label_custom_categoria">Categoria</label>
                    </div>
                    <div class="col-3">
                        <select name="categoria" id="inputState" class="form-control">
                            <option selected value="">Todas las Categorias</option>
                            
                            {% for c in categoria  %}
                            <option value="{{c.nombre}}">{{c.nombre}}</option>
                            {% endfor %}                               
                            
                        </select>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="row ">
                        <div class="col-4">
                            <button name="tipo" class="btn btn-default boton-custom"  type="button" onclick="preview()" value="1">Preview <i
                                    class="fa fa-eye fa-2x" aria-hidden="true"></i></button>
                        </div>
                        <div class="col-4">
                            <button name="tipo" class="btn btn-primary boton-custom" type="submit" value="2">Generar
                                Reporte en PDF <i class="fa fa-file-pdf-o fa-2x" aria-hidden="true"></i></button>
                        </div>
                        <div class="col-4">
                            <button name="tipo" class="btn btn-success boton-custom" type="submit" value="3">Generar
                                Reporte en xls <i class="fa fa-file-excel-o fa-2x" aria-hidden="true"></i></button>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
    <div class="container" style="position: relative; top:20px; display:none" id='id_tile'>
            <div class="tile" style="border: black solid">
                    <h3 class="tile-title">Preview</h3>
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Producto</th>
                          <th>Categoria</th>
                          <th>Cantidad</th>
                          <th>Ganancia</th>
                          <th>Inventario</th>
                        </tr>
                      </thead>
                      <tbody id='table'>
 
                      </tbody>
                    </table>
                  </div>
    </div>
    {% endblock contenido %}


    {% block plugins %}

    {% include "base/conf_fechas.html" %}
    <script type="text/javascript">
        // using jQuery get csrftoken from your HTML
            var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    // if not safe, set csrftoken
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            function preview(){


                $.ajax({
                    url: "{% url 'tactico:semire_producto_generan_ganancia' %}",
                    method:'POST',
                    data: {
                        // here getdata should be a string so that
                        // in your views.py you can fetch the value using get('getdata')
                        'tipo': 1,
                        'categoria': $("#inputState").children("option:selected").val(),
                        'fechainicio':$("#id_fechainicio").val(),
                        'fechafin':$("#id_fechafin").val()


                    },
                    dataType: 'json',
                    success: function (res, status) {
                        if(Array.isArray(res)){
                            $("#error_fechainicio").hide()
                            $("#error_fechafin").hide()
                            $("#id_tile").show()
                            console.log(res)
                            var table=$("#table");
                            $("#table").html("")
                            res.forEach(function(elemento){
                            table.append("<tr><td>"+elemento.idProducto__nombre+"</td><td>"
                            +(elemento.idProducto__idCategoria__nombre==null?$("#inputState").children("option:selected").val():elemento.idProducto__idCategoria__nombre)+
                            "</td>   <td>"+elemento.cantidad__sum+
                            "</td><td>"+elemento.ganancia+"</td><td>"+elemento.inventario+"</td></tr>");
                            }
                            );
                        }
                        else{
                            $("#error_fechainicio").hide()
                            $("#error_fechafin").hide()
                            $("#id_tile").hide()
                           
                            obj=JSON.parse(res)
                            if(obj.fechafin!=null){
                                $("#error_fechafin").show()
                                $("#error_fechafin").html(obj.fechafin[0].message)
                            }
                            if(obj.fechainicio!=null){
                                $("#error_fechainicio").show()
                                $("#error_fechainicio").html(obj.fechainicio[0].message)
                            }
                        }
                    },
                    error: function (res) {
                        console.log(res);                                                                                                                          
                    }
                });
            }
        </script>
    {% endblock plugins %}