sgCibercachadas/sgCibercachadas/administrador/urls.py
from django.urls import include, path
from administrador.views import AdminUsuariosView,CrearUsuariosView,InhabilitarUsuarios,EditarUsuariosView,BitacorasView

urlpatterns = [
    path('adminusuarios',AdminUsuariosView.as_view(),name='admin_gestion_usuarios'),
    path('crearusuarios',CrearUsuariosView.as_view(),name='admin_crear_usuarios'),
    path('editarusuarios/<int:id>',EditarUsuariosView.as_view(),name='admin_editar_usuarios'),
    path('inhabilitar/<int:id>',InhabilitarUsuarios.as_view(),name="admin_inhabilitar_usuarios"),
    path('bitacoras',BitacorasView.as_view(),name="admin_bitacora_usuarios")
]

sgCibercachadas/sgCibercachadas/estrategico/urls.py
from django.urls import include, path
from estrategico.views import *

urlpatterns = [
    path('productosgeneranganancias',ProductosGeneranGananciasView.as_view(),name='re_producto_generan_ganancias'),
    path('productospotenciales',ProductosPotencialesView.as_view(),name='re_producto_potenciales'),
    path('productosgananciasclientes',ProductosGananciasClientesView.as_view(),name='re_producto_ganancias_clientes'),
    path('productosmasvendidos',ProductosVendidosView.as_view(),name='re_producto_vendido'),
    path('productostardanzaproductos',ProductosTardanzaProductosView.as_view(),name='re_producto_tardanza_productos'),
]

sgCibercachadas/sgCibercachadas/etl/urls.py
from django.urls import include,path
from etl.views import *

urlpatterns = [
    path('',CargaDatos.as_view(),name="carga_menu"),
    path('cargabd',EtlBD.as_view(),name="etl_bd"),
    path('cargaretorno',CargaRetorno.as_view(),name='etl_retorno'),
    path('cargapotencial',CargaPotencial.as_view(),name='etl_potencial'),
    path('cargaconsigna',CargaConsigna.as_view(),name='etl_consigna')
    

]

sgCibercachadas/sgCibercachadas/general/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from general.views import *
from general.views import Home

urlpatterns = [
    path('',Home.as_view(),name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='general/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='general/login.html'),name='logout'),
    path('perfil',PerfilView.as_view()),
    path('perfil/cambiar',PerfilPasswordView.as_view())
]

sgCibercachadas/sgCibercachadas/sgCibercachadas/urls.py
from django.urls import include,path

urlpatterns = [
    path('',include(('general.urls','general'),namespace='general')),
    path('resumen/',include(('estrategico.urls','estrategico'),namespace='estrategico')),
    path('semiresumen/',include(('tactico.urls','tactico'),namespace='tactico')),
    path('admin/',include(('administrador.urls','administrador'),namespace='administrador')),
    path('etl/',include(('etl.urls','etl'),namespace='etl'))
]

sgCibercachadas/sgCibercachadas/tactico/urls.py
from django.urls import include, path
from tactico.views import *

urlpatterns = [
    path('productosmasvendidos',ProductosMasVendidosView.as_view(),name='semire_producto_mas_vendidos'),
    path('productosgeneranganancia',ProductosGeneranGananciaView.as_view(),name='semire_producto_generan_ganancia'),
    path('retornoequiposgarantia',RetornoEquiposGarantiaView.as_view(),name='semire_retorno_equipos_garantia'),
    path('productosenconsigna',RetornoEnConsignaView.as_view(),name='semire_productos_consigna'),
    path('clientesganancia',ClientesGananciaView.as_view(),name='semire_clientes_ganancia'),
    path('clientesfrecuentes',ClientesFrecuentesView.as_view(),name='semire_clientes_frecuentes'),
]

sgCibercachadas/sgCibercachadas/templates/base/base.html
{% load static %}

{% load helpers %}
<!DOCTYPE html>
<html lang="es">
    <head>  
        <title>
            {% block head_title %}
            Principal
            {% endblock head_title %}
        </title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Main CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <!-- Font-icon css-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    </head>
        <body class="app sidebar-mini rtl">
                <!-- Navbar-->
            <header class="app-header"><a class="app-header__logo" href="/">CiberCachadas</a>
                  <!-- Sidebar toggle button--><a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
                  <!-- Navbar Right Menu-->
            {% if user.is_authenticated %}
            <ul class="app-nav">
            <!-- User Menu-->
                <li class="dropdown"><a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
                    <ul class="dropdown-menu settings-menu dropdown-menu-right">
                        <li><a class="dropdown-item" href="/perfil"><i class="fa fa-user fa-lg"></i> Perfil</a></li>
                        <li><a class="dropdown-item" href="/"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
                        <li><a class="dropdown-item" href="{% url 'general:logout' %}"><i class="fa fa-sign-out fa-lg"></i> Cerrar sesión</a></li>
                    </ul>
                </li>
            </ul>
            {% endif %}
            </header>
                <!-- Sidebar menu-->
      
            <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
            {% if user.is_authenticated %}
              <aside class="app-sidebar">
                  <div class="app-sidebar__user"><img class="app-sidebar__user-avatar" src="{% static '/img/user.png' %}" alt="User Image">
                    <div>
                      <p class="app-sidebar__user-name">{{user.username}}</p>
                      <p class="app-sidebar__user-designation">{{user.groups.first| default_if_none:"" }}</p>
                    </div>
                  </div>
                  <ul class="app-menu">
                    {% if request.user|has_group:"Estrategico" %} 
                        <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-folder-open-o"></i><span class="app-menu__label">Reportes Estrategicos</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                            <ul class="treeview-menu">

                              {% if perms.gerencial.resumen_productos_ganancias %}                     
                              <li><a class="treeview-item " href="{% url 'estrategico:re_producto_generan_ganancias' %}"><i class="icon fa fa-circle-o"></i> Productos con Ganancias</a></li>
                              {% endif %}
                              {% if perms.gerencial.resumen_productos_potenciales %}                               
                              <li><a class="treeview-item" href="{% url 'estrategico:re_producto_potenciales' %}"><i class="icon fa fa-circle-o"></i> Productos Potenciales</a></li>
                              {% endif %}
                              {% if perms.gerencial.resumen_ganancias_clientes %}
                              <li><a class="treeview-item" href="{% url 'estrategico:re_producto_ganancias_clientes' %}"><i class="icon fa fa-circle-o"></i> Ganancia de Clientes</a></li>
                              {% endif %}
                              {% if perms.gerencial.resumen_productos_vendidos %}
                              <li><a class="treeview-item" href="{% url 'estrategico:re_producto_vendido' %}"><i class="icon fa fa-circle-o"></i> Productos Más Vendidos</a></li>
                             {% endif %}
                             {% if perms.gerencial.resumen_tardanzas_productos %}
                             <li><a class="treeview-item" href="{% url 'estrategico:re_producto_tardanza_productos' %}"><i class="icon fa fa-circle-o"></i>Tardanza Movimiento </a></li>
                            {% endif %}
                            </ul>
                        </li>
                        {% endif %}               

                        {% if request.user|has_group:"Tactico" %} 
                        <li class="treeview "><a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-folder-open-o"></i><span class="app-menu__label">Reportes Tacticos</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                            <ul class="treeview-menu">
                              

                              {% if perms.gerencial.semi_productos_vendidos %}
                              <li><a class="treeview-item " href="{% url 'tactico:semire_producto_mas_vendidos' %}"><i class="icon fa fa-circle-o"></i> Productos mas Vendidos</a></li>
                              {% endif %}
                              {% if perms.gerencial.semi_productos_ganancias %}
                              <li><a class="treeview-item" href="{% url 'tactico:semire_producto_generan_ganancia' %}" ><i class="icon fa fa-circle-o"></i> Productos Generan Ganancia</a></li>
                              {% endif %}
                              {% if perms.gerencial.semi_retornos_equipos %}
                              <li><a class="treeview-item" href="{% url 'tactico:semire_retorno_equipos_garantia' %}" ><i class="icon fa fa-circle-o"></i> Retorno de equipos </a></li>
                              {% endif %}
                              {% if perms.gerencial.semi_productos_consigna %}
                              <li><a class="treeview-item" href="{% url 'tactico:semire_productos_consigna' %}" ><i class="icon fa fa-circle-o"></i>    Productos en Consigna </a></li>
                              {% endif %}
                              {% if perms.gerencial.semi_ganancias_clientes %}
                              <li><a class="treeview-item" href="{% url 'tactico:semire_clientes_ganancia' %}" ><i class="icon fa fa-circle-o"></i> Ganancias de Clientes</a></li>
                              {% endif %}
                              {%if perms.gerencial.semi_clientes_frecuentes %}
                              <li><a class="treeview-item" href="{% url 'tactico:semire_clientes_frecuentes' %}" ><i class="icon fa fa-circle-o"></i> Clientes Frecuentes </a></li>
                              {% endif %}
                            </ul>
                        </li>
                        {% endif %}
                        {% if request.user|has_group:"Administrador" %} 
                       
                        <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-laptop"></i><span class="app-menu__label">Gestión de Usuarios</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                          <ul class="treeview-menu">
                                {% if perms.gerencial.gestion_usuarios %}
                                <li><a class="treeview-item" href="{% url 'administrador:admin_gestion_usuarios' %}" ><i class="icon fa fa-circle-o"></i> Listado de Usuarios</a></li>
                                {% endif %}
                                {% if perms.gerencial.gestion_usuarios %}
                                <li><a class="treeview-item" href="{% url 'administrador:admin_crear_usuarios' %}" ><i class="icon fa fa-circle-o"></i> Crear Usuarios</a></li>
                                {% endif %}
                                {% if perms.gerencial.gestion_usuarios %}
                                <li><a class="treeview-item" href="{% url 'administrador:admin_bitacora_usuarios' %}" ><i class="icon fa fa-circle-o"></i> Bitacora Usuarios</a></li>
                                {% endif %}
                          </ul>
                        </li>
                        <li><a class="app-menu__item" href="{% url 'etl:carga_menu'%}"><i class="app-menu__icon fa fa-database"></i><span class="app-menu__label">ETL</span></a></li>
                        {% endif %}
                       
                    </ul>


                </aside>
                {% endif %}
            <main class="app-content">
                <div class="app-title">
                    <div>
                      <h1><i class="fa fa-dashboard"></i> {% block titulo_principal %} Black {% endblock titulo_principal %}</h1>
                      <p>{% block mensaje_titulo %} Black {% endblock mensaje_titulo %}</p>
                    </div>
                    <ul class="app-breadcrumb breadcrumb">
                      <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
                      <li class="breadcrumb-item">{% block enlace_actual %} Black {% endblock enlace_actual %}</li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                      <div class="tile">
                        <div class="tile-body">
                            {% block contenido %} Black {% endblock contenido %}
                        </div>
                      </div>
                    </div>
                </div>
            </main>
               <!-- Essential javascripts for application to work-->
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script  src="{% static 'js/plugins/bootstrap-datepicker.min.js' %}"></script>
            <!-- The javascript plugin to display page loading on top-->
        <script src="{% static 'js/plugins/pace.min.js' %}"></script>
        {% block plugins %}
        
        {% endblock plugins%}
    </body>
</html>

sgCibercachadas/sgCibercachadas/templates/base/conf_fechas.html
<script type="text/javascript">
    $.fn.datepicker.dates['es'] = {
        days: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
        daysShort: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
        daysMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sá"],
        months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre",
            "Octubre", "Noviembre", "Diciembre"
        ],
        monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
        today: "Hoy",
        clear: "Borrar",
        format: "dd/mm/yyyy",
        titleFormat: "MM yyyy",
        /* Leverages same syntax as 'format' */
        weekStart: 0
    };


    $('#id_fechainicio').datepicker({
        format: "dd/mm/yyyy",
        autoclose: true,
        todayHighlight: true,
        language: 'es',
    });


    $('#id_fechafin').datepicker({
        format: "dd/mm/yyyy",
        autoclose: true,
        todayHighlight: true,
        language: 'es'

    });
   
</script>

sgCibercachadas/sgCibercachadas/templates/base/fechas_snippet.html
<div class="row">
    <div class="col-6">
        <div class="form-group row">
            <label class="control-label col-3" id="label_custom">Fecha Inicio</label>
            {{form.fechainicio}}           
             <i class="fa fa-calendar fa-2x col-3" aria-hidden="true"></i>
             {% if form.fechainicio.errors %}
             <div class="form-control-feedback col-6 text-danger"> {{form.fechainicio.errors.0}}</div>
             {% endif %}
             <div class="form-control-feedback col-6 text-danger" id="error_fechainicio" style="display: none"> </div>
        </div>
    </div>
    <div class="col-6">
        <div class="form-group row">
            <label class="control-label col-3" id="label_custom">Fecha Fin</label>
            
            {{form.fechafin}}
            <i class="fa fa-calendar fa-2x col-3" aria-hidden="true"></i>
            {% if form.fechafin.errors %}
            <div class="form-control-feedback col-5 text-danger"> {{form.fechafin.errors.0}}</div>
            {% endif %}
            <div class="form-control-feedback col-6 text-danger" id="error_fechafin" style="display: none"> </div>
        </div>
    </div>
</div>
   