sgCibercachadas/sgCibercachadas/etl/urls.py
from django.urls import include,path
from etl.views import *

urlpatterns = [
    path('',CargaDatos.as_view(),name="carga_menu"),
    path('cargabd',EtlBD.as_view(),name="etl_bd"),
    path('cargaretorno',CargaRetorno.as_view(),name='etl_retorno'),
    path('cargapotencial',CargaPotencial.as_view(),name='etl_potencial'),
    path('cargaconsigna',CargaConsigna.as_view(),name='etl_consigna')
    

]

sgCibercachadas/sgCibercachadas/sgCibercachadas/urls.py
from django.urls import include,path

urlpatterns = [
    path('',include(('general.urls','general'),namespace='general')),
    path('resumen/',include(('estrategico.urls','estrategico'),namespace='estrategico')),
    path('semiresumen/',include(('tactico.urls','tactico'),namespace='tactico')),
    path('admin/',include(('administrador.urls','administrador'),namespace='administrador')),
    path('etl/',include(('etl.urls','etl'),namespace='etl'))
]

sgCibercachadas/sgCibercachadas/etl/models.py
from django.db import models

# Create your models here.

sgCibercachadas/sgCibercachadas/etl/forms.py
from django import forms
from django.core.validators import FileExtensionValidator

class RetornoForm(forms.Form):
    file_retorno=forms.FileField(validators=[FileExtensionValidator(['xlsx'])])

class PotencialForm(forms.Form):
    file_potencial=forms.FileField(validators=[FileExtensionValidator(['xlsx'])])
    
class ConsignaForm(forms.Form):
    file_consigna=forms.FileField(validators=[FileExtensionValidator(['xlsx'])])

sgCibercachadas/sgCibercachadas/etl/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.views import generic
from django.contrib import messages
from django.utils import timezone
from datetime import datetime,timezone
from etl.forms import RetornoForm, PotencialForm,ConsignaForm
from gerencial.models import *
from subprocess import Popen, PIPE
import openpyxl

class CargaDatos(LoginRequiredMixin,PermissionRequiredMixin,generic.TemplateView):
    template_name='etl/index.html'
    login_url='general:login'
    permission_required = 'gerencial.etl'

    def get(self,request,*args,**kwargs):
        return render(request, self.template_name)

class EtlBD(LoginRequiredMixin,PermissionRequiredMixin,generic.TemplateView):
    login_url='general:login'
    permission_required = 'gerencial.etl'

    def get(self,request,*args,**kwargs):
        return redirect('/etl')

    def post(self,request,*args,**kwargs):
        script_dir="../../ETL/etlSGcachadas"
        p = Popen(["python", "main.py"], cwd=script_dir, stdout=PIPE, stderr=PIPE)
        print(p.communicate())
        
        #bitacora 
        Bitacora.objects.create(
        usuario=request.user.first_name+" "+request.user.last_name,
        accion="Ejecucion ETL (Script) ",
        )

        messages.add_message(request, messages.SUCCESS, 'ETL ejecutado con exito')
        return redirect('/etl')

class CargaRetorno(LoginRequiredMixin,PermissionRequiredMixin,generic.TemplateView):
    login_url='general:login'
    permission_required = 'gerencial.etl'

    def get(self,request,*args,**kwargs):
        return redirect('/etl')
        
    def post(self,request,*args,**kwargs):
        form= RetornoForm(request.POST,request.FILES)
        if form.is_valid():             
            archivo=request.FILES.get("file_retorno")
            archivo= openpyxl.load_workbook(archivo)
            hoja1=archivo.get_sheet_by_name('Hoja1')
            max_row = hoja1.max_row
            for row in hoja1.iter_rows(min_row=5, max_col=6, max_row=max_row):
                i = 0
                retorno = ProductoRetorno()
                for cell in row:     
                    i += 1
                    if i==2:
                        if cell.value:
                            retorno.fecha = cell.value
                        else:
                            break
                    if i==3:
                        if cell.value:
                            try:
                                producto = Producto.objects.get(codigo=cell.value)
                                retorno.idProducto = producto
                                retorno.nombre_producto = producto.nombre
                                retorno.codigo = producto.codigo
                            except Producto.DoesNotExist:
                                retorno.nombre_producto = None
                        else:
                            break
                    if i==4:
                        if cell.value:
                            try:
                                cliente = Cliente.objects.get(nombre=cell.value) 
                                retorno.idCliente = cliente
                                retorno.nombre_cliente = cell.value 
                            except Cliente.DoesNotExist:
                                retorno.nombre_cliente = None
                        else:
                            break
                    if i==5:
                        if cell.value:
                            try:
                                proveedor = Proveedor.objects.get(razon_social=cell.value)
                                retorno.idProveedor = proveedor
                                nombre_proveedor = proveedor.razon_social
                            except Proveedor.DoesNotExist:
                                nombre_proveedor = None
                        else:
                            break
                    if i==6:
                        if cell.value:
                            retorno.cantidad = cell.value
                        else:
                            break
                if(retorno.nombre_producto and retorno.nombre_cliente and nombre_proveedor):
                    retorno.save()
                    #bitacora 
                    Bitacora.objects.create(
                    usuario=request.user.first_name+" "+request.user.last_name,
                    accion="Carga productos retorno (.xls) ",
                    )   
                      

            messages.add_message(request, messages.SUCCESS, 'Carga de producto retorno realizada con exito')
            return redirect('etl:carga_menu')
        else:
            return render(request,'etl/index.html',{'form':form})
            

class CargaPotencial(LoginRequiredMixin,PermissionRequiredMixin,generic.TemplateView):
    login_url='general:login'
    permission_required = 'gerencial.etl'

    def get(self,request,*args,**kwargs):
        return redirect('/etl')
    
    def post(self,request,*args,**kwargs):
        form= PotencialForm(request.POST,request.FILES)
        if form.is_valid():            
            archivo=request.FILES.get("file_potencial")
            archivo= openpyxl.load_workbook(archivo)
            hoja1=archivo.get_sheet_by_name('Hoja1')
            max_row = hoja1.max_row
            for row in hoja1.iter_rows(min_row=5, max_col=5, max_row=max_row):
                i=0
                producto = ProductoPotencial()
                nombre_cliente = None
                for cell in row:
                    i+=1
                    if(i==2):
                        if(cell.value):
                            producto.fecha = cell.value
                        else:
                            break
                    if(i==3):
                        if(cell.value):
                            try:
                                nombre_cliente = cell.value
                                producto.idCliente = Cliente.objects.get(nombre=nombre_cliente)
                            except Cliente.DoesNotExist:
                                nombre_cliente = None
                        else:
                            break
                    if(i==4):
                        if(cell.value):
                            producto.nombre = cell.value
                        else:
                            break
                    if(i==5):
                        if(cell.value):
                            producto.cantidad = cell.value
                        else:
                            break
                if(nombre_cliente):
                    producto.save()


            messages.add_message(request, messages.SUCCESS, 'Carga de producto potenciales realizada con exito')
            return redirect('etl:carga_menu')
        else:
            return render(request,'etl/index.html',{'form':form})


class CargaConsigna(LoginRequiredMixin,PermissionRequiredMixin,generic.TemplateView):
    login_url='general:login'
    permission_required = 'gerencial.etl'

    def get(self,request,*args,**kwargs):
        return redirect('/etl')
    
    def post(self,request,*args,**kwargs):
        form= ConsignaForm(request.POST,request.FILES)
        if form.is_valid():
            archivo=request.FILES.get("file_consigna")
            archivo= openpyxl.load_workbook(archivo)
            hoja1=archivo.get_sheet_by_name('Hoja1')
            max_row = hoja1.max_row
            for row in hoja1.iter_rows(min_row=5, max_col=6, max_row=max_row):
                i=0
                consigna = ProductoConsigna()
                cliente = None
                producto = None
                for cell in row:
                    i+=1
                    if(i==2):
                        if(cell.value):
                            consigna.fechaInicio = cell.value
                        else:
                            break
                    if(i==3):
                        if(cell.value):
                            consigna.fechaFin = cell.value
                        else:
                            break
                    if(i==4):
                        if(cell.value):
                            try:
                                producto = Producto.objects.get(codigo = cell.value)
                                consigna.idProducto = producto
                            except Producto.DoesNotExist:
                                producto = None
                        else:
                            break
                    if(i==5):
                        if(cell.value):
                            try:
                                cliente = Cliente.objects.get(nombre=cell.value)
                                consigna.idCliente = cliente
                            except Cliente.DoesNotExist:
                                cliente = None
                        else:
                            break
                    if(i==6):
                        if(cell.value):
                            consigna.cantidad = cell.value
                        else:
                            break
                if(producto and cliente):
                    consigna.save()
            messages.add_message(request, messages.SUCCESS, 'Carga de productos en consigna realizada con exito')
            return redirect('etl:carga_menu')
        else:
            return render(request,'etl/index.html',{'form':form})

sgCibercachadas/sgCibercachadas/etl/templates/etl/index.html
{% extends 'base/base.html' %}
{% block head_title %}
ETL
{% endblock head_title %}
{% block titulo_principal %}
Sección de carga del ETL
{% endblock titulo_principal %}
{% block mensaje_titulo %}
Aqui se puede realizar la carga de archivos ademas la ejecución manual del ETL para la extraccion de registros de la base de datos 
transaccional
{% endblock mensaje_titulo %}
{% block enlace_actual %}
<a href="{% url 'etl:carga_menu' %}">Seccion ETL</a>
{% endblock enlace_actual %}
{% block contenido %}
{% if messages %}
{% for message in messages %}
<li{% if message.tags %} class="alert alert-{{ message.tags }} text-center" {% endif %}>
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
    {{ message }}
    </li>
    {% endfor %}
  {% endif %}
<div class="row">
    <div class="col-md-6">
        <div class="tile" >
            <div class="overlay" id="loading_etl" style="display:none">
                <div class="m-loader mr-4">
                  <svg class="m-circular" viewBox="25 25 50 50">
                    <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="4" stroke-miterlimit="10"></circle>
                  </svg>
                </div>
                <h3 class="l-text">Ejecutando ETL...</h3>
              </div>
                <h3 class="tile-title">ETL</h3>
                <div class="tile-body">
                    Cargar los datos de los registros en las tablas necesarias
                    de la base de datos transaccional a la base de datos que usa este
                    sistema informatico
                </div>
                <div class="tile-footer">
                    <form action="{% url 'etl:etl_bd' %}" method="post">
                        {% csrf_token %}
                    <div class="text-center">
                        <button class="btn btn-outline-primary " id='etl_button' type="submit">Ejecutar ETL</button>
                    </div>
                    </form>
                </div>
              </div>
            </div>
<div class="col-md-6">
    <div class="tile">
        <div class="overlay" id="loading_retorno" style="display:none">
            <div class="m-loader mr-4">
              <svg class="m-circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="4" stroke-miterlimit="10"></circle>
              </svg>
            </div>
            <h3 class="l-text">Cargando archivo productos retornos...</h3>
          </div>

    <div class="tile-title-w-btn">
      <h3 class="title">Retorno de productos</h3>
      <div class="btn-group">
          <a class="btn btn-success" href="/static/formatos/retornogarantiaformato.xlsx">Formato Ejemplo  <i class="fa fa-lg fa-file-excel-o "></i></a></div>
    </div>
    <div class="tile-body">
        Cargar los datos de los productos retornados por los clientes, en un formato .xlsx para dejarlos almacenados en la base de datos que usa este sistema
        informatico
        <form action="{% url 'etl:etl_retorno'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
        <input class="form-control" type="file" name="file_retorno" >
        {% if form.file_retorno.errors %}
        <div class="form-control-feedback text-danger"> {{form.file_retorno.errors.0}}</div>
        {% endif %}
    </div>
    <div class="tile-footer">
      <div class="text-center">
          <button class="btn btn-outline-primary " id="retorno" type="submit">Ejecutar Carga</button>
        </form>   
      </div>
  </div>
  </div>
</div>
  <div class="col-md-6">
  <div class="tile">
      <div class="overlay" id="loading_potencial" style="display:none">
          <div class="m-loader mr-4">
            <svg class="m-circular" viewBox="25 25 50 50">
              <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="4" stroke-miterlimit="10"></circle>
            </svg>
          </div>
          <h3 class="l-text">Cargando archivo productos potenciales</h3>
        </div>
    <div class="tile-title-w-btn">
      <h3 class="title">Productos potenciales</h3>
      <div class="btn-group">
                    <a class="btn btn-success" href="/static/formatos/productopotencialformato.xlsx">Formato Ejemplo  <i class="fa fa-lg fa-file-excel-o "></i></a></div>
    </div>
    <div class="tile-body">
      Cargar los datos de los productos potenciales, en un formato .xlsx para dejarlos almacenados en la base de datos que usa este sistema
      informatico      
      <form action="{% url 'etl:etl_potencial'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <input class="form-control" type="file" name="file_potencial" >
      {% if form.file_potencial.errors %}
      <div class="form-control-feedback text-danger"> {{form.file_potencial.errors.0}}</div>
      {% endif %}
    </div>
    <div class="tile-footer">
      <div class="text-center">
          <button class="btn btn-outline-primary " id="potencial" type="submit">Ejecutar Carga</button>
      </form>
        </div>
  </div>
  </div>
</div>

<div class="col-md-6">
  <div class="tile">
      <div class="overlay" id="loading_consigna" style="display:none">
          <div class="m-loader mr-4">
            <svg class="m-circular" viewBox="25 25 50 50">
              <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="4" stroke-miterlimit="10"></circle>
            </svg>
          </div>
          <h3 class="l-text">Cargando archivo productos en consigna.</h3>
        </div>
    <div class="tile-title-w-btn">
      <h3 class="title">Productos en consigna</h3>
      <div class="btn-group">
                <a class="btn btn-success" href="/static/formatos/productoconsignaformato.xlsx" download>Formato Ejemplo  <i class="fa fa-lg fa-file-excel-o "></i></a></div>
    </div>
    <div class="tile-body">
      Cargar los datos de los productos en estado consigna, en un formato .xlsx para dejarlos almacenados en la base de datos que usa este sistema
      informatico        
      <form action="{% url 'etl:etl_consigna'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <input class="form-control" type="file" name="file_consigna" >
      {% if form.file_consigna.errors %}
      <div class="form-control-feedback text-danger"> {{form.file_consigna.errors.0}}</div>
      {% endif %}
    </div>
    <div class="tile-footer">
      <div class="text-center">
          <button class="btn btn-outline-primary " id="consigna" type="submit">Ejecutar carga</button>
      </form>
      </div>
  </div>
  </div>
</div>
</div>
{% endblock contenido %}


{% block plugins %}
<script>
let submitETL=document.getElementById("etl_button")
let submitRetorno= document.getElementById("retorno")
let submitPotencial= document.getElementById("potencial")
let submitConsigna= document.getElementById("consigna")

let loadingETL= document.getElementById("loading_etl")
let loadingRetorno= document.getElementById("loading_retorno")
let loadingPotencial= document.getElementById("loading_potencial")
let loadingConsigna=document.getElementById("loading_consigna")

//se ejecuta loading despues de 0.7 segundos
submitETL.addEventListener('click',function(ev){
  setTimeout(function(){
    submitETL.setAttribute("style","display:none")
    loadingETL.style.display="inline-flex"
  },700);
})
submitRetorno.addEventListener('click',function(ev){
  setTimeout(function(){
    submitETL.setAttribute("style","display:none")
    loadingRetorno.style.display="inline-flex"
  },700);
})
submitPotencial.addEventListener('click',function(ev){
  setTimeout(function(){
    submitETL.setAttribute("style","display:none")
    loadingPotencial.style.display="inline-flex"
  },700);
})
submitConsigna.addEventListener('click',function(ev){
  setTimeout(function(){
    submitConsigna.setAttribute("style","display:none")
    loadingConsigna.style.display="inline-flex"
  },700);
})

</script>
{% endblock plugins %}