sgCibercachadas/sgCibercachadas/administrador/urls.py
from django.urls import include, path
from administrador.views import AdminUsuariosView,CrearUsuariosView,InhabilitarUsuarios,EditarUsuariosView,BitacorasView

urlpatterns = [
    path('adminusuarios',AdminUsuariosView.as_view(),name='admin_gestion_usuarios'),
    path('crearusuarios',CrearUsuariosView.as_view(),name='admin_crear_usuarios'),
    path('editarusuarios/<int:id>',EditarUsuariosView.as_view(),name='admin_editar_usuarios'),
    path('inhabilitar/<int:id>',InhabilitarUsuarios.as_view(),name="admin_inhabilitar_usuarios"),
    path('bitacoras',BitacorasView.as_view(),name="admin_bitacora_usuarios")
]

sgCibercachadas/sgCibercachadas/etl/urls.py
from django.urls import include,path
from etl.views import *

urlpatterns = [
    path('',CargaDatos.as_view(),name="carga_menu"),
    path('cargabd',EtlBD.as_view(),name="etl_bd"),
    path('cargaretorno',CargaRetorno.as_view(),name='etl_retorno'),
    path('cargapotencial',CargaPotencial.as_view(),name='etl_potencial'),
    path('cargaconsigna',CargaConsigna.as_view(),name='etl_consigna')
    

]

sgCibercachadas/sgCibercachadas/sgCibercachadas/urls.py
from django.urls import include,path

urlpatterns = [
    path('',include(('general.urls','general'),namespace='general')),
    path('resumen/',include(('estrategico.urls','estrategico'),namespace='estrategico')),
    path('semiresumen/',include(('tactico.urls','tactico'),namespace='tactico')),
    path('admin/',include(('administrador.urls','administrador'),namespace='administrador')),
    path('etl/',include(('etl.urls','etl'),namespace='etl'))
]

sgCibercachadas/sgCibercachadas/administrador/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User

class UsuarioForm(forms.Form):
    
    username=forms.CharField(widget=forms.TextInput(attrs={"name":"username" ,
    "class":"form-control ","placeholder":"Escriba Username","autocomplete":"off",}))

    nombres=forms.CharField(widget=forms.TextInput(attrs={"name":"nombres" ,
    "class":"form-control ","placeholder":"Escriba sus nombres","autocomplete":"off"},))

    apellidos=forms.CharField(widget=forms.TextInput(attrs={"name":"apellidos" ,
    "class":"form-control ","placeholder":"Escriba sus apellidos","autocomplete":"off"},))

    email=forms.CharField(required=False,widget=forms.TextInput(attrs={"name":"email" ,
    "class":"form-control ","placeholder":"Escriba su email","type":"email","autocomplete":"off"},))

    password=forms.CharField(widget=forms.TextInput(attrs={"name":"password" ,
    "class":"form-control ","placeholder":"Escriba su contraseña","type":"password","autocomplete":"new-password"},))

    password2=forms.CharField(widget=forms.TextInput(attrs={"name":"password2" ,
    "class":"form-control ","placeholder":"Escriba su contraseña","type":"password","autocomplete":"off"},))


    def AddIsInvalid(self):
        for field in self.errors:
            self[field].field.widget.attrs['class'] += ' is-invalid'

    def clean(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        username=self.cleaned_data.get("username")
        email=self.cleaned_data.get("email")
        usernameDB=User.objects.filter(username=username).first()
        emailDB=User.objects.filter(email=email).first()

        if  len(username)<=4:
            self.add_error('username','El nombre de usuario debe contener almenos 4 caracteres')

        if usernameDB:
                self.add_error('username','El nombre de usuario ya existe')
        
        if emailDB and emailDB.email!='':
                self.add_error('email','el email ya existe para el usuario')

        if password!=password2:
            self.add_error('password',"Las contraseñas no coinciden")
        if len(password)< 8 :
            self.add_error('password',"La contraseña debe ser mayor que 8 caracter")
        if not (any(x.isupper() for x in password) and any(x.islower() for x in password)  and any(x.isdigit() for x in password)):
            self.add_error('password',"La contraseña debe al menos una letra en mayuscula, una letra en minuscula, un digito")


class UsuarioEditForm(forms.Form):
    
    username=forms.CharField(widget=forms.TextInput(attrs={"name":"username" ,
    "class":"form-control ","placeholder":"Escriba Username","autocomplete":"off"}))
    nombres=forms.CharField(widget=forms.TextInput(attrs={"name":"nombres" ,
    "class":"form-control ","placeholder":"Escriba sus nombres","autocomplete":"off"},))
    apellidos=forms.CharField(widget=forms.TextInput(attrs={"name":"apellidos" ,
    "class":"form-control ","placeholder":"Escriba sus apellidos","autocomplete":"off"},))
    email=forms.CharField(required=False,widget=forms.TextInput(attrs={"name":"email" ,

    "class":"form-control ","placeholder":"Escriba su email","type":"email","autocomplete":"off"},))
    
    def __init__(self, *args, **kwargs):
        self.id = kwargs.pop('id', None)
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        

    def AddIsInvalid(self):
        for field in self.errors:
            self[field].field.widget.attrs['class'] += ' is-invalid'

    def clean(self):

        #data already cleaned for the custom validations at the top
        username=self.cleaned_data.get("username")
        email=self.cleaned_data.get("email")
        
        #getting the values in case these are existing on db, excluding the current id on the url
        usernameDB=User.objects.filter(username=username).exclude(id=self.id).first()
        emailDB=User.objects.filter(email=email).exclude(id=self.id).first()

        if  len(username)<=4:
            self.add_error('username','El nombre de usuario debe contener almenos 4 caracteres')

        if usernameDB:
                self.add_error('username','El nombre de usuario ya existe')
        
        if emailDB and emailDB.email!='':
                self.add_error('email','el email ya existe para el usuario')

sgCibercachadas/sgCibercachadas/administrador/views.py
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.views import generic
from django.views.generic.list import ListView
from django.contrib.auth.models import User
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.models import Group
from django.contrib import messages
from django.http import Http404
from gerencial.models import Bitacora
from datetime import datetime
from administrador.forms import *
from plantilla_reporte.bitacorapdf.bitacora import reporte

class AdminUsuariosView(LoginRequiredMixin,PermissionRequiredMixin,generic.ListView):
    model = User
    template_name='administrador/admin_usuarios.html'
    login_url='general:login'
    permission_required = 'gerencial.gestion_usuarios'
    context_object_name = "obj"
    ordering=['-id']
    paginate_by = 6


class CrearUsuariosView(LoginRequiredMixin,PermissionRequiredMixin,generic.TemplateView):
   
    template_name='administrador/crear_usuarios.html'
    login_url='general:login'
    permission_required = 'gerencial.gestion_usuarios'

    def get(self,request,*args,**kwargs):
        form= UsuarioForm()
        return render(request,self.template_name,{"form":form})    
    def post(self,request,*args,**kwargs):   
        form= UsuarioForm(request.POST)
        if form.is_valid():
            my_group = get_object_or_404(Group, pk=request.POST.get('rol'))

            #en caso de que el grupo no sea permitido
            if my_group.id!=3:


                user = User.objects.create_user(
                                    username=request.POST.get('username'),
                                    first_name=request.POST.get('nombres'),
                                    last_name=request.POST.get('apellidos'),
                                    email=request.POST.get('email'),
                                    password=request.POST.get('password'))

                my_group.user_set.add(user)

                Bitacora.objects.create(
                    usuario=request.user.first_name+" "+request.user.last_name,
                    accion="Registro usuario: "+request.POST.get('username')+", Perfil: "+my_group.name,
                    )

                messages.add_message(request, messages.SUCCESS, 'Ingreso del Usuario con Username: '
                +request.POST.get('username')+' Contraseña: '+request.POST.get('password'))
            else:
                messages.add_message(request, messages.WARNING, 'Perfil de acceso no permitido ')
            return redirect(self.request.path_info)
        else:
            form.AddIsInvalid()
            return render(request,self.template_name,{"form":form})

class InhabilitarUsuarios(LoginRequiredMixin,PermissionRequiredMixin,generic.TemplateView):
    template_name="administrador/admin_usuarios.html"
    login_url='general:login'
    permission_required = 'gerencial.gestion_usuarios'

    def post(self,request,*args, **kwargs):
        user= get_object_or_404(User, pk=self.kwargs['id'])
        user.is_active= (True,False)[user.is_active]   
        user.save()

        #bitacora
        Bitacora.objects.create(
        usuario=request.user.first_name+" "+request.user.last_name,
        accion=("Deshabilitar","Habilitar")[user.is_active]+
        " usuario: "+user.username,
        )
        return redirect("administrador:admin_gestion_usuarios")




class EditarUsuariosView(LoginRequiredMixin,PermissionRequiredMixin,generic.TemplateView):
    template_name='administrador/editar_usuarios.html'
    login_url='general:login'
    permission_required = 'gerencial.gestion_usuarios'


    def get(self,request,*args,**kwargs):
        usuario= get_object_or_404(User, pk=self.kwargs['id'])

        form= UsuarioEditForm(initial={
        "username":usuario.username,
        "nombres":usuario.first_name,
        "apellidos":usuario.last_name,
        "email":usuario.email}
        )

        return render(request,self.template_name,{
        "form":form,
        "group":usuario.groups.all()[0].id,
        "groups":Group.objects.all()}
        )

    def post(self,request,*args,**kwargs):   
        form= UsuarioEditForm(request.POST, id=self.kwargs['id'])
        current_user=User.objects.filter(pk=self.kwargs["id"]).first()
        
        if form.is_valid():
           
            #accesing through the user to its groups
            user_groups = User.groups.through.objects.get(user=current_user)
            #overriding the rol from the form
            user_groups.group= get_object_or_404(Group, pk=request.POST.get('rol'))

            #only update if the group has id not equals to 3 (admin user).
            if user_groups.group.id!=3:
                user_groups.save()
                Bitacora.objects.create(
                    usuario=request.user.first_name+" "+request.user.last_name,
                    accion="Editar usuario: "+request.POST.get('username'),
                    )
             

            #updating only the user data 
            User.objects.filter(pk=self.kwargs['id']).update(username=request.POST.get("username"),
            first_name=request.POST.get("nombres"), last_name=request.POST.get("apellidos"),email=request.POST.get("email"))

            messages.add_message(request, messages.SUCCESS, 'Actualizacion del Usuario con Username: '
            +request.POST.get('username'))

            return redirect(self.request.path_info)
        else:
        
            form.AddIsInvalid()
            return render(request,self.template_name,{"form":form,"group":current_user.groups.all()[0].id,
        "groups":Group.objects.all()})

class BitacorasView(LoginRequiredMixin, generic.ListView):
    template_name='administrador/bitacora_usuarios.html'
    login_url='general:login'
    permission_required = 'gerencial.gestion_usuarios'   
    
    model = Bitacora
    context_object_name = "obj"
    ordering=['-id']
    paginate_by = 10
    def get_queryset(self):
        query = self.request.GET.get('fecha')
        if query!='' and query:
            datetime_object = datetime.strptime(query, '%d/%m/%Y')
            object_list = self.model.objects.filter(fecha__gte = datetime_object)
        else:
            object_list = self.model.objects.all()
        return object_list
    
    def post(self,request,*args,**kwargs):
        print(request.GET.get('fecha'))
        bitacora = int(request.POST.get('bitacora'))
        if(bitacora == 1):
            data = self.model.objects.all()
            return reporte(request,data,'bitacora')

sgCibercachadas/sgCibercachadas/administrador/templates/administrador/admin_usuarios.html
{% extends 'base/base.html' %}
{% block head_title %}
Administración de Usuarios
{% endblock head_title %}
{% block titulo_principal %}
Administración de Usuarios
{% endblock titulo_principal %}
{% block mensaje_titulo %}
Administración de Usuarios
{% endblock mensaje_titulo %}
{% block enlace_actual %}
<a href="{% url 'administrador:admin_gestion_usuarios' %}">Administración de Usuarios</a>
{% endblock enlace_actual %}
{% block contenido %}
<div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="dataTables_length" id="sampleTable_length">
                <a class="btn btn-success" href="{% url 'administrador:admin_crear_usuarios' %}"><i
                        class="fa fa-user-plus" aria-hidden="true"></i>Crear Usuario</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid"
                aria-describedby="sampleTable_info">
                <thead>
                    <tr role="row">
                        <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1"
                            aria-sort="ascending" style="width: 65px;">
                            Username</th>
                        <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1"
                            style="width: 137px;">
                            Nombres</th>
                        <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1"
                            style="width: 135px;">
                            Apellidos</th>
                        <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1"
                            style="width: 145px;">
                            Email</th>
                        <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1">
                            Perfil</th>

                        <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1"
                            style="width: 183px;">
                            Acciones</th>
                </thead>
                <tbody>
                    {% for item in obj %}
                    {% if item.groups.first.name != 'Administrador'  %}
                    <tr role="row" class="odd">
                        <td>{{ item.username }}</td>
                        <td>{{ item.first_name }}</td>
                        <td>{{ item.last_name }}</td>
                        <td>{{ item.email }}</td>
                        <td>{{ item.groups.first.name }}</td>
                        {% if item.is_active %}
                        <td>
                            <a class="btn btn-primary"
                                href="{% url 'administrador:admin_editar_usuarios' id=item.id %}"><i
                                    class="fa fa-pencil-square-o" aria-hidden="true"></i>Editar</a>
                            <form action="{% url 'administrador:admin_inhabilitar_usuarios' id=item.id %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-warning" type=submit><i class="fa fa-user-times"
                                    aria-hidden="true"></i>Deshabilitar</button>
                            </form>
                        </td>
                        {% else %}
                        <td>

                            <form action="{% url 'administrador:admin_inhabilitar_usuarios' id=item.id %}" method="post">
                                    {% csrf_token %}

                                <button class="btn btn-primary" type=submit><i class="fa fa-unlock"
                                    aria-hidden="true"></i>Habilitar</button>
                            </form>
                        </td>
                        {% endif %}
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            <div class="dataTables_paginate paging_simple_numbers" id="sampleTable_paginate">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="paginate_button page-item previous" id="sampleTable_previous">
                        <a href="?page={{ page_obj.previous_page_number }}" aria-controls="sampleTable" data-dt-idx="0"
                            tabindex="0" class="page-link">
                            Anterior
                        </a>
                    </li>
                    {% endif %}

                    {% if page_obj.has_next %}
                    <li class="paginate_button page-item previous" id="sampleTable_previous">
                        <a href="?page={{ page_obj.next_page_number }}" aria-controls="sampleTable" data-dt-idx="0"
                            tabindex="0" class="page-link">
                            Siguiente
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        {% endblock contenido %}

sgCibercachadas/sgCibercachadas/administrador/templates/administrador/bitacora_usuarios.html
{% extends 'base/base.html' %}
{% block head_title %}
Administración de Usuarios
{% endblock head_title %}
{% block titulo_principal %}
Bitacora de Usuarios
{% endblock titulo_principal %}
{% block mensaje_titulo %}
Bitacora de usuarios
{% endblock mensaje_titulo %}
{% block enlace_actual %}
<a href="{% url 'administrador:admin_bitacora_usuarios' %}">Bitacora de Usuarios</a>
{% endblock enlace_actual %}
{% block contenido %}
<div id="sampleTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
<div class="row">
        <form class="form-inline">
                <div class="form-group mx-sm-3 mb-2">
                  <label for="search" class="sr-only">Fecha</label>
                  <input type="text" class="form-control" id="fecha" name="fecha" placeholder="Desde fecha" autocomplete="off">
                </div>
                <button type="submit" class="btn btn-primary mb-2">Buscar <i class="fa fa-search" aria-hidden="true"></i></button>
        </form>
        <form method="POST">
            {% csrf_token %}
            &nbsp;&nbsp;&nbsp;<button type="submit" class="btn btn-primary-outline mb-2" name="bitacora" value="1">Generar PDF <i class="fa fa-file-pdf-o" aria-hidden="true"></i></button>
        </form>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover table-bordered dataTable no-footer" id="sampleTable" role="grid"
                aria-describedby="sampleTable_info">
                <thead>
                    <tr role="row">
                        <th class="sorting_asc" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1"
                            aria-sort="ascending" style="width: 65px;">
                            Fecha</th>
                        <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1"
                            style="width: 137px;">
                            Usuario Que Realiza Accion</th>
                        <th class="sorting" tabindex="0" aria-controls="sampleTable" rowspan="1" colspan="1"
                            style="width: 135px;">
                            Acciones</th>
 
                </thead>
                <tbody>
                    {% for item in obj %}
                    <tr role="row" class="odd">
                        <td>{{ item.fecha }}</td>
                        <td>{{ item.usuario }}</td>
                        <td>{{ item.accion }}</td>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="dataTables_paginate paging_simple_numbers" id="sampleTable_paginate">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="paginate_button page-item previous" id="sampleTable_previous">
                        <a href="?fecha={{ request.GET.search }}&?page={{ page_obj.previous_page_number }}" aria-controls="sampleTable" data-dt-idx="0"
                            tabindex="0" class="page-link">
                            Anterior
                        </a>
                    </li>
                    {% endif %}

                    {% if page_obj.has_next %}
                    <li class="paginate_button page-item previous" id="sampleTable_previous">
                        <a href="?fecha={{ request.GET.search }}&?page={{ page_obj.next_page_number }}" aria-controls="sampleTable" data-dt-idx="0"
                            tabindex="0" class="page-link">
                            Siguiente
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        {% endblock contenido %}

        {% block plugins %}
        <script type="text/javascript">
            $.fn.datepicker.dates['es'] = {
                days: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
                daysShort: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
                daysMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sá"],
                months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre",
                    "Octubre", "Noviembre", "Diciembre"
                ],
                monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
                today: "Hoy",
                clear: "Borrar",
                format: "dd/mm/yyyy",
                titleFormat: "MM yyyy",
                /* Leverages same syntax as 'format' */
                weekStart: 0
            };
        
        
            $('#fecha').datepicker({
                format: "dd/mm/yyyy",
                autoclose: true,
                todayHighlight: true,
                language: 'es',
            });

        </script>
        
        {% endblock plugins %}

sgCibercachadas/sgCibercachadas/administrador/templates/administrador/crear_usuarios.html
{% extends 'base/base.html' %}
{% block head_title %}
Crear Usuario
{% endblock head_title %}
{% block titulo_principal %}
Crear Usuario
{% endblock titulo_principal %}
{% block mensaje_titulo %}
Crear Usuario
{% endblock mensaje_titulo %}
{% block enlace_actual %}
<a href="{% url 'administrador:admin_crear_usuarios' %}">Crear Usuario</a>
{% endblock enlace_actual %}
{% block contenido %}
{% if messages %}
{% for message in messages %}
<li{% if message.tags %} class="alert alert-{{ message.tags }} text-center" {% endif %}>
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
    {{ message }}
    </li>
    {% endfor %}
{% endif %}
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
            <label class="control-label">Username</label>
            {{form.username}}
            {% if form.username.errors %}
            <div class="form-control-feedback col-6 text-danger"> {{form.username.errors.0}}</div>
            {% endif %}
          </div>
          <div class="form-group">
            <label class="control-label">Nombres</label>
            {{form.nombres}}
            {% if form.nombres.errors %}
            <div class="form-control-feedback col-6 text-danger"> {{form.nombres.errors.0}}</div>
            {% endif %}
          </div>
          <div class="form-group">
              <label class="control-label">Apellidos</label>
              {{form.apellidos}}
              {% if form.apellidos.errors %}
              <div class="form-control-feedback col-6 text-danger"> {{form.apellidos.errors.0}}</div>
              {% endif %}
          </div>
          <div class="form-group">
                <label class="control-label">Email</label>
                {{form.email}}
                {% if form.email.errors %}
                <div class="form-control-feedback col-6 text-danger"> {{form.email.errors.0}}</div>
                {% endif %}
            </div>
          <div class="form-group">
              <label class="control-label">Contraseña</label>
              {{form.password}}
              {% if form.password.errors %}
              <div class="form-control-feedback col-6 text-danger"> {{form.password.errors.0}}</div>
              {% endif %}
          </div>
          <div class="form-group">
              <label class="control-label">Ingrese nuevamente Contraseña</label>
              {{form.password2}}
              {% if form.password2.errors %}
              <div class="form-control-feedback col-6 text-danger"> {{form.password2.errors.0}}</div>
              {% endif %}
        </div>
        <div class="form-group">
                <label class="control-label">Perfil de acceso</label>
                <div class="form-check">
                  <label class="form-check-label">
                    <input class="form-check-input" type="radio" checked name="rol" value=2>Tactico
                  </label>
                </div>
                <div class="form-check">
                  <label class="form-check-label">
                    <input class="form-check-input" type="radio" name="rol" value=1>Estrategico
                  </label>
                </div>
        </div>
        <div class="tile-footer">
                <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Registrar</button>&nbsp;&nbsp;&nbsp;<a class="btn btn-secondary" href="/admin/adminusuarios"><i class="fa fa-fw fa-lg fa-times-circle"></i>Cancelar</a>
              </div>
  </form>

{% endblock contenido %}

sgCibercachadas/sgCibercachadas/administrador/templates/administrador/editar_usuarios.html
{% extends 'base/base.html' %}
{% block head_title %}
Editar Usuario
{% endblock head_title %}
{% block titulo_principal %}
Editar Usuario
{% endblock titulo_principal %}
{% block mensaje_titulo %}
Editar Usuario
{% endblock mensaje_titulo %}
{% block enlace_actual %}
<a href="">Editar Usuario</a>
{% endblock enlace_actual %}
{% block contenido %}
{% if messages %}
{% for message in messages %}
<li{% if message.tags %} class="alert alert-{{ message.tags }} text-center" {% endif %}>
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
    {{ message }}
    </li>
    {% endfor %}
{% endif %}
<form method="POST" autocomplete="off">
    {% csrf_token %}
    <div class="form-group">
            <label class="control-label">Username</label>
            {{form.username}}
            {% if form.username.errors %}
            <div class="form-control-feedback col-6 text-danger"> {{form.username.errors.0}}</div>
            {% endif %}
          </div>
          <div class="form-group">
            <label class="control-label">Nombres</label>
            {{form.nombres}}
            {% if form.nombres.errors %}
            <div class="form-control-feedback col-6 text-danger"> {{form.nombres.errors.0}}</div>
            {% endif %}
          </div>
          <div class="form-group">
              <label class="control-label">Apellidos</label>
              {{form.apellidos}}
              {% if form.apellidos.errors %}
              <div class="form-control-feedback col-6 text-danger"> {{form.apellidos.errors.0}}</div>
              {% endif %}
          </div>
          <div class="form-group">
                <label class="control-label">Email</label>
                {{form.email}}
                {% if form.email.errors %}
                <div class="form-control-feedback col-6 text-danger"> {{form.email.errors.0}}</div>
                {% endif %}
            </div>
         
        <div class="form-group">
                <label class="control-label">Perfil de acceso</label>
                {% for role in groups %}
                {% if role.id != 3 %} 
                <div class="form-check">  
                  <label class="form-check-label">
                    <input class="form-check-input" type="radio" {% if role.id == group %} checked {% endif %} name="rol" value="{{role.id}}">{{role.name}}
                  </label>
                </div>  
                {% endif %}
                {% endfor %}
    
        </div>
        <div class="tile-footer">
                <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-pencil"></i>Actualizar</button>&nbsp;&nbsp;&nbsp;<a class="btn btn-secondary" href="/admin/adminusuarios"><i class="fa fa-fw fa-lg fa-times-circle"></i>Cancelar</a>
              </div>
  </form>

{% endblock contenido %}